### ISSUE TITLE
how can we use it puppeteer?

### ISSUE THREAD

**Issue by Galileo1** [holsee/chroxy#37]
Any suggestions? [Puppetter Api](https://github.com/GoogleChrome/puppeteer/blob/v1.18.1/docs/api.md#puppeteerconnectoptions)

**Comment by holsee** [comment]
Chroxy only supports exposing "Page" sessions, it would appear from the connections options exposed by puppetter that it requires "Browser" sessions. 

```
browserWSEndpoint <?string> a browser websocket endpoint to connect to.
browserURL <?string> a browser url to connect to, in format http://${host}:${port}. Use interchangeably with browserWSEndpoint to let Puppeteer fetch it from metadata endpoint.
```
