### ISSUE TITLE
Chrome Flags

### ISSUE THREAD

**Issue by shamil614** [holsee/chroxy#51]
I'm working on a project with a forked version of Chroxy. There are all sorts of reasons why we are using a fork but ideally we want to use the main line code base going forward. One issue is that we have a bunch of flags set for Chrome here's what our config looks like (there are even more flags in our config) 😆 

```
chrome_flags: [
    "--user-agent=\"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36\"",
    "--disable-dev-shm-usage",
    "--disable-features=VizDisplayCompositor",
    "--enable-features=NetworkService,NetworkServiceInProcess",
    "--headless",
    "--disable-gpu",
    "--no-sandbox",
    "--ignore-certificate-errors",
    "--incognito",
    "--allow-running-insecure-content",
    "--v8-cache-options=off",
    "--aggressive-cache-discard",
    "--disable-cache",
    "--disable-application-cache",
    "--disable-offline-load-stale-cache",
    "--no-first-run"
  ]
```
Also we were planning on using the Docker version of Chroxy. As such, I'm trying to figure out how to make these flags configurable with the app and docker.

**Comment by holsee** [comment]
I am open to ideas on how this could be overwritten, at the end of the day it is a list of strings so the presence of a chrome_flags file could be enough to signal that it be read and applied at build time versus the default.

**Comment by evadne** [comment]
@shamil614 I suggest using `config/runtime.exs` which was added as part of Elixir 1.11. As to Docker, it should make no difference
