### ISSUE TITLE
Proxy configuration per-connection

### ISSUE THREAD

**Issue by Taik** [holsee/chroxy#7]
Hi! Are there plans to have a new mode which allows consumers to specify their own proxy configuration? I don't think it's possible to specify proxy configuration on a per-tab basis.

I believe you eluded to it here https://github.com/holsee/chroxy/issues/5#issuecomment-398787429; I wanted to get the conversation rolling around implementation ideas.

**Comment by holsee** [comment]
What configuration are you talking about in particular? I would need more information on this scenario to make an informed response.

**Comment by Taik** [comment]
The `--proxy-server` flag that's passed to the chrome process upon launching, specifically.

**Comment by holsee** [comment]
This would only be an application level configuration option at this time, not one that could be pass per connection - as each connection is to a Page, not a Browser.

**Comment by holsee** [comment]
As you correctly alluded to, we may extend this to allow for Browser connections to be exposed at which point this could be passed in.  I would welcome a patch that would add this functionality if it was really useful.
